# Generated by Django 4.2.13 on 2024-06-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=5)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='api.jugador')),
            ],
        ),
        migrations.DeleteModel(
            name='Programador',
        ),
    ]
