# Generated by Django 4.2.13 on 2024-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carta_delete_programador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='cambio',
            field=models.IntegerField(default=0),
        ),
    ]
